version: "3.9"

x-test-framework: jest

x-service:
  &service
  build:
    context: .
  volumes:
    - type: volume
      source: output
      target: $ENGI_WORKING_DIR

services:
  storybook:
    command: npm run storybook
    <<: *service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6007"]
      timeout: 60s
      retries: 3
  tests:
    command: /bin/sh -c "jest --json | tee $ENGI_WORKING_DIR/jest.json"
    <<: *service
    depends_on:
      storybook:
        condition: service_healthy
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
