version: "3.9"

x-test-framework: jest

x-service:
  &service
  build:
    context: .
  volumes:
    - type: volume
      source: output
      target: $ENGI_WORKING_DIR

services:
  storybook:
    command: npm run storybook
    <<: *service
  tests:
    command: /bin/sh -c "jest --json | tee $ENGI_WORKING_DIR/jest.json"
    <<: *service
    depends_on:
      - storybook
volumes:
  output:
    external: true
    name: $ENGI_WORKING_VOL
